version: '3'

services: 
    app:
        build: ./Frontend
        image: cryptoprices-app
        ports:
            - 80:80
        networks: 
            - frontend

    api:
        build: ./Backend
        image: cryptoprices-api
        environment: 
            - PORT=5000
            - API_KEY=$API_KEY
        ports:
            - 5000:5000
        networks: 
            - frontend
            - backend

    redis:
        image: redis:6.0.6-alpine
        networks:
            - backend

networks:
    frontend:
    backend: